[package]
name = "deploy"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
arcs-deploy-logging = { version = "0.1.0", path = "arcs-deploy-logging" }
chrono = "0.4.21"
arcs-deploy-docker = { version = "0.1.0", path = "arcs-deploy-docker" }
eager = "0.1.0"
lazy_static = "1.4.0"
paste = "1.0.8"
smallvec = "1.9.0"
tokio = "1.20.1"
tokio-postgres = "0.7.6"
unstringify = "0.1.4"
arcs-yaml-verifier = { version = "0.1.0", path = "arcs-yaml-verifier" }
dotenv = "0.15.0"
arcs-deploy-shared-structs = { version = "0.1.0", path = "arcs-deploy-shared-structs" }
arcs-deploy-k8s = { version = "0.1.0", path = "arcs-deploy-k8s" }
openssl = { version = "0.10", features = ["vendored"] }
serde = "1.0.145"
serde_json = "1.0.85"
secstr = "0.5.1"
guard = "0.5.1"
sha2 = "0.10.6"
hmac = "0.12.1"
hex = "0.4.3"

[build-dependencies]
walkdir = "2.3.2"
