[package]
name = "arcs-yaml-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
marked-yaml = "0.5"
serde = { version = "1", features = ["derive"] }
yaml-rust = { version = "0.8", package = "yaml-rust2" }
