use arcs_env_rs::*;

env_var_req!(PORT);

env_var_req!(WEBHOOK_SERVER_AUTH_TOKEN -> WEBHOOK_TOKEN);
env_var_req!(DEPLOY_SERVER_AUTH_TOKEN -> DEPLOY_TOKEN);

env_var_req!(WEBHOOK_SERVER_ADDRESS -> WEBHOOK_ADDRESS);
env_var_req!(DEPLOY_SERVER_ADDRESS -> DEPLOY_ADDRESS);
env_var_req!(S3_BUCKET_URL -> S3_ADDRESS);
env_var_req!(S3_DISPLAY_URL -> S3_DISPLAY_ADDRESS);

env_var_req!(GIT_INTEGRATION_EMAIL -> GIT_EMAIL);
env_var_req!(GIT_DEPLOY_BRANCH_NAME -> GIT_BRANCH);
env_var_req!(GIT_SSH_KEY_PATH -> GIT_KEY_PATH);

assert_req_env!(check_env_vars:
    PORT,
    DEPLOY_TOKEN, WEBHOOK_TOKEN, WEBHOOK_ADDRESS,
    DEPLOY_ADDRESS, S3_ADDRESS, S3_DISPLAY_ADDRESS,
    GIT_EMAIL, GIT_BRANCH, GIT_KEY_PATH
);


